import type { ChatConversation } from '../../../components/chat/chatTypes'

export const chatbotMonitorConversations: ChatConversation[] = [
  {
    id: 'conv-1204',
    sessionCode: '1204',
    patientName: 'Nguyễn Văn A',
    patientAge: 42,
    branch: 'Chi nhánh A',
    specialty: 'Nội tổng quát',
    handlerType: 'doctor',
    riskLevel: 'urgent',
    rating: 2,
    feedback: 'Tôi được chuyển sang bác sĩ nhưng vẫn muốn được cảnh báo rõ hơn ngay từ đầu.',
    doctorName: 'Nguyễn Minh An',
    takeoverTime: '09:18',
    lastMessage: 'Tôi sẽ đặt lịch khám trực tiếp trong hôm nay cho anh.',
    updatedMinutesAgo: 6,
    symptoms: ['Sốt 39 độ', 'Đau đầu dữ dội', 'Ho khan', 'Mệt lả'],
    botSummary: 'Nghi ngờ sốt xuất huyết hoặc nhiễm trùng cấp. Bot khuyến nghị đi khám ngay và chuyển bác sĩ.',
    messages: [
      { id: 'm-1204-1', sender: 'patient', text: 'Tôi sốt cao từ đêm qua, đau đầu nhiều và rất mệt.', time: '09:10' },
      { id: 'm-1204-2', sender: 'chatbot', text: 'Anh đang sốt bao nhiêu độ và có kèm chảy máu cam hoặc phát ban không?', time: '09:11' },
      { id: 'm-1204-3', sender: 'patient', text: 'Khoảng 39 độ, người đau nhức, chưa thấy phát ban.', time: '09:12' },
      { id: 'm-1204-4', sender: 'chatbot', text: 'Triệu chứng có dấu hiệu nguy cơ. Anh nên được bác sĩ đánh giá trực tiếp trong ngày.', time: '09:13' },
      { id: 'm-1204-5', sender: 'system', text: '🤖 Chatbot dừng tư vấn — 🩺 Bác sĩ Nguyễn Minh An đã tham gia cuộc hội thoại', time: '09:18' },
      { id: 'm-1204-6', sender: 'doctor', doctorName: 'BS. Nguyễn Minh An', avatarLabel: 'NA', text: 'Tôi sẽ đặt lịch khám trực tiếp trong hôm nay cho anh.', time: '09:20' },
    ],
  },
  {
    id: 'conv-1205',
    sessionCode: '1205',
    patientName: 'Trần Mai Hương',
    patientAge: 55,
    branch: 'Chi nhánh B',
    specialty: 'Tim mạch',
    handlerType: 'doctor',
    riskLevel: 'urgent',
    rating: 4,
    feedback: 'Bác sĩ phản hồi nhanh, hướng dẫn rõ khi nào cần đi cấp cứu.',
    doctorName: 'Lê Quốc Bảo',
    takeoverTime: '10:02',
    lastMessage: 'Nếu còn đau ngực lan tay trái, chị đến cấp cứu ngay.',
    updatedMinutesAgo: 14,
    symptoms: ['Đau ngực', 'Khó thở', 'Vã mồ hôi'],
    botSummary: 'Có dấu hiệu cảnh báo tim mạch. Bot chuyển bác sĩ và khuyến nghị cấp cứu nếu triệu chứng tăng.',
    messages: [
      { id: 'm-1205-1', sender: 'patient', text: 'Tôi đau tức ngực, hơi khó thở và toát mồ hôi.', time: '09:56' },
      { id: 'm-1205-2', sender: 'chatbot', text: 'Cơn đau có lan ra tay trái, hàm hoặc lưng không ạ?', time: '09:57' },
      { id: 'm-1205-3', sender: 'patient', text: 'Có hơi lan sang vai trái.', time: '09:58' },
      { id: 'm-1205-4', sender: 'system', text: '🤖 Chatbot dừng tư vấn — 🩺 Bác sĩ Lê Quốc Bảo đã tham gia cuộc hội thoại', time: '10:02' },
      { id: 'm-1205-5', sender: 'doctor', doctorName: 'BS. Lê Quốc Bảo', avatarLabel: 'QB', text: 'Nếu còn đau ngực lan tay trái, chị đến cấp cứu ngay.', time: '10:04' },
    ],
  },
  {
    id: 'conv-1206',
    sessionCode: '1206',
    patientName: 'Phạm Gia Minh',
    patientAge: 7,
    branch: 'Chi nhánh C',
    specialty: 'Nhi khoa',
    handlerType: 'bot',
    riskLevel: 'normal',
    rating: 1,
    feedback: 'Câu trả lời khó hiểu, tôi cần gặp người thật thay vì chỉ nhận hướng dẫn chung.',
    lastMessage: 'Tôi không hiểu hướng dẫn này, cần gặp người thật.',
    updatedMinutesAgo: 22,
    symptoms: ['Ho nhẹ', 'Sổ mũi', 'Sốt 37.8 độ'],
    botSummary: 'Triệu chứng hô hấp nhẹ, bot hướng dẫn theo dõi tại nhà nhưng người dùng đánh giá thấp.',
    messages: [
      { id: 'm-1206-1', sender: 'patient', text: 'Bé nhà tôi ho nhẹ và sổ mũi từ sáng.', time: '08:40' },
      { id: 'm-1206-2', sender: 'chatbot', text: 'Anh/chị cho bé uống đủ nước, vệ sinh mũi và theo dõi nhiệt độ mỗi 4 giờ.', time: '08:42' },
      { id: 'm-1206-3', sender: 'patient', text: 'Tôi không hiểu hướng dẫn này, cần gặp người thật.', time: '08:45' },
    ],
  },
  {
    id: 'conv-1207',
    sessionCode: '1207',
    patientName: 'Lê Thanh Tâm',
    patientAge: 29,
    branch: 'Chi nhánh A',
    specialty: 'Da liễu',
    handlerType: 'bot',
    riskLevel: 'normal',
    rating: 5,
    feedback: 'Hướng dẫn dễ làm theo, tôi biết khi nào cần đặt lịch khám.',
    lastMessage: 'Tôi sẽ thử theo hướng dẫn và theo dõi thêm.',
    updatedMinutesAgo: 31,
    symptoms: ['Ngứa da', 'Nổi mẩn đỏ nhẹ'],
    botSummary: 'Có thể là kích ứng da nhẹ. Bot hướng dẫn tránh tác nhân kích ứng và đặt lịch nếu lan rộng.',
    messages: [
      { id: 'm-1207-1', sender: 'patient', text: 'Tôi nổi mẩn đỏ ở cổ tay sau khi đổi sữa tắm.', time: '08:25' },
      { id: 'm-1207-2', sender: 'chatbot', text: 'Chị tạm ngưng sản phẩm mới, rửa vùng da bằng nước sạch và theo dõi 24 giờ.', time: '08:27' },
      { id: 'm-1207-3', sender: 'patient', text: 'Tôi sẽ thử theo hướng dẫn và theo dõi thêm.', time: '08:29' },
    ],
  },
  {
    id: 'conv-1208',
    sessionCode: '1208',
    patientName: 'Hoàng Nhật Linh',
    patientAge: 34,
    branch: 'Chi nhánh B',
    specialty: 'Tiêu hóa',
    handlerType: 'doctor',
    riskLevel: 'normal',
    rating: 3,
    feedback: 'Thông tin ổn nhưng tôi vẫn cần bác sĩ xác nhận thêm.',
    doctorName: 'Phạm Hoài Thu',
    takeoverTime: '08:12',
    lastMessage: 'Tôi sẽ kê lịch khám tiêu hóa sáng mai cho chị.',
    updatedMinutesAgo: 48,
    symptoms: ['Đau bụng âm ỉ', 'Buồn nôn', 'Ăn kém'],
    botSummary: 'Triệu chứng tiêu hóa kéo dài, chưa có dấu hiệu cấp cứu nhưng cần bác sĩ đánh giá.',
    messages: [
      { id: 'm-1208-1', sender: 'patient', text: 'Tôi đau bụng âm ỉ ba ngày nay và hơi buồn nôn.', time: '08:05' },
      { id: 'm-1208-2', sender: 'chatbot', text: 'Chị có nôn ra máu, đi ngoài phân đen hoặc đau dữ dội không?', time: '08:06' },
      { id: 'm-1208-3', sender: 'patient', text: 'Không có, chỉ âm ỉ và ăn kém.', time: '08:08' },
      { id: 'm-1208-4', sender: 'system', text: '🤖 Chatbot dừng tư vấn — 🩺 Bác sĩ Phạm Hoài Thu đã tham gia cuộc hội thoại', time: '08:12' },
      { id: 'm-1208-5', sender: 'doctor', doctorName: 'BS. Phạm Hoài Thu', avatarLabel: 'HT', text: 'Tôi sẽ kê lịch khám tiêu hóa sáng mai cho chị.', time: '08:14' },
    ],
  },
  {
    id: 'conv-1209',
    sessionCode: '1209',
    patientName: 'Đỗ Minh Khang',
    patientAge: 38,
    branch: 'Chi nhánh C',
    specialty: 'Cơ xương khớp',
    handlerType: 'bot',
    riskLevel: 'normal',
    rating: 2,
    feedback: 'Câu trả lời hơi chung chung, tôi muốn được đặt lịch khám nhanh hơn.',
    lastMessage: 'Câu trả lời hơi chung chung, tôi cần lịch khám.',
    updatedMinutesAgo: 64,
    symptoms: ['Đau lưng', 'Tê chân nhẹ'],
    botSummary: 'Đau lưng sau vận động, bot hướng dẫn nghỉ ngơi và gợi ý đặt lịch nếu tê tăng.',
    messages: [
      { id: 'm-1209-1', sender: 'patient', text: 'Tôi đau lưng sau khi bê đồ nặng, chân hơi tê.', time: '07:58' },
      { id: 'm-1209-2', sender: 'chatbot', text: 'Anh nên nghỉ ngơi, chườm ấm và tránh bê nặng. Nếu tê lan rộng, hãy đặt lịch khám.', time: '08:00' },
      { id: 'm-1209-3', sender: 'patient', text: 'Câu trả lời hơi chung chung, tôi cần lịch khám.', time: '08:02' },
    ],
  },
  {
    id: 'conv-1210',
    sessionCode: '1210',
    patientName: 'Vũ Hồng Nhung',
    patientAge: 31,
    branch: 'Chi nhánh A',
    specialty: 'Sản phụ khoa',
    handlerType: 'doctor',
    riskLevel: 'urgent',
    rating: 5,
    feedback: 'Bác sĩ tiếp quản rất nhanh và hướng dẫn rõ ràng.',
    doctorName: 'Trần Thảo Vy',
    takeoverTime: '07:44',
    lastMessage: 'Chị cần đến cơ sở gần nhất để kiểm tra ngay.',
    updatedMinutesAgo: 79,
    symptoms: ['Đau bụng dưới', 'Ra máu bất thường', 'Chóng mặt'],
    botSummary: 'Ca sản phụ khoa nguy cơ cao, bot chuyển bác sĩ ngay.',
    messages: [
      { id: 'm-1210-1', sender: 'patient', text: 'Tôi đau bụng dưới và ra máu bất thường.', time: '07:39' },
      { id: 'm-1210-2', sender: 'chatbot', text: 'Chị có chóng mặt, choáng hoặc đau tăng nhanh không?', time: '07:40' },
      { id: 'm-1210-3', sender: 'patient', text: 'Có hơi chóng mặt.', time: '07:41' },
      { id: 'm-1210-4', sender: 'system', text: '🤖 Chatbot dừng tư vấn — 🩺 Bác sĩ Trần Thảo Vy đã tham gia cuộc hội thoại', time: '07:44' },
      { id: 'm-1210-5', sender: 'doctor', doctorName: 'BS. Trần Thảo Vy', avatarLabel: 'TV', text: 'Chị cần đến cơ sở gần nhất để kiểm tra ngay.', time: '07:46' },
    ],
  },
  {
    id: 'conv-1211',
    sessionCode: '1211',
    patientName: 'Bùi Anh Tuấn',
    patientAge: 27,
    branch: 'Chi nhánh B',
    specialty: 'Tai mũi họng',
    handlerType: 'bot',
    riskLevel: 'normal',
    rating: 4,
    feedback: 'Chatbot trả lời phù hợp với tình trạng nhẹ của tôi.',
    lastMessage: 'Cảm ơn, tôi sẽ súc họng và theo dõi thêm.',
    updatedMinutesAgo: 92,
    symptoms: ['Đau họng', 'Khàn tiếng'],
    botSummary: 'Viêm họng nhẹ, bot hướng dẫn chăm sóc tại nhà và theo dõi sốt.',
    messages: [
      { id: 'm-1211-1', sender: 'patient', text: 'Tôi đau họng và khàn tiếng sau khi đi mưa.', time: '07:20' },
      { id: 'm-1211-2', sender: 'chatbot', text: 'Anh súc họng nước muối ấm, uống nước ấm và theo dõi nếu sốt hoặc khó thở.', time: '07:22' },
      { id: 'm-1211-3', sender: 'patient', text: 'Cảm ơn, tôi sẽ súc họng và theo dõi thêm.', time: '07:24' },
    ],
  },
  {
    id: 'conv-1212',
    sessionCode: '1212',
    patientName: 'Ngô Mỹ Duyên',
    patientAge: 46,
    branch: 'Chi nhánh C',
    specialty: 'Nội tiết',
    handlerType: 'doctor',
    riskLevel: 'normal',
    rating: 5,
    feedback: 'Tôi hài lòng vì bác sĩ hỏi đúng thông tin chỉ số cần thiết.',
    doctorName: 'Đặng Thanh Sơn',
    takeoverTime: '06:50',
    lastMessage: 'Anh/chị gửi giúp chỉ số đường huyết gần nhất để tôi xem.',
    updatedMinutesAgo: 118,
    symptoms: ['Khát nước nhiều', 'Mệt mỏi', 'Sụt cân nhẹ'],
    botSummary: 'Triệu chứng gợi ý rối loạn đường huyết. Bot chuyển bác sĩ để đánh giá chỉ số.',
    messages: [
      { id: 'm-1212-1', sender: 'patient', text: 'Gần đây tôi rất khát nước và mệt, có sụt cân nhẹ.', time: '06:42' },
      { id: 'm-1212-2', sender: 'chatbot', text: 'Chị có kết quả đường huyết hoặc tiền sử tiểu đường không ạ?', time: '06:43' },
      { id: 'm-1212-3', sender: 'system', text: '🤖 Chatbot dừng tư vấn — 🩺 Bác sĩ Đặng Thanh Sơn đã tham gia cuộc hội thoại', time: '06:50' },
      { id: 'm-1212-4', sender: 'doctor', doctorName: 'BS. Đặng Thanh Sơn', avatarLabel: 'TS', text: 'Anh/chị gửi giúp chỉ số đường huyết gần nhất để tôi xem.', time: '06:51' },
    ],
  },
  {
    id: 'conv-1213',
    sessionCode: '1213',
    patientName: 'Cao Phương Anh',
    patientAge: 24,
    branch: 'Chi nhánh A',
    specialty: 'Tâm lý',
    handlerType: 'doctor',
    riskLevel: 'urgent',
    rating: 3,
    feedback: 'Tôi cần hỗ trợ trực tiếp nhiều hơn nhưng phản hồi ban đầu ổn.',
    doctorName: 'Mai Gia Linh',
    takeoverTime: '06:18',
    lastMessage: 'Tôi sẽ ở đây và kết nối chị với hỗ trợ khẩn cấp.',
    updatedMinutesAgo: 146,
    symptoms: ['Mất ngủ', 'Hoảng loạn', 'Ý nghĩ tự làm hại'],
    botSummary: 'Có tín hiệu nguy cơ tự hại, bot chuyển bác sĩ và gợi ý hỗ trợ khẩn cấp.',
    messages: [
      { id: 'm-1213-1', sender: 'patient', text: 'Tôi mất ngủ nhiều ngày và có lúc nghĩ đến việc làm hại bản thân.', time: '06:10' },
      { id: 'm-1213-2', sender: 'chatbot', text: 'Tôi rất tiếc vì chị đang trải qua điều này. Chị có đang ở một mình không?', time: '06:11' },
      { id: 'm-1213-3', sender: 'system', text: '🤖 Chatbot dừng tư vấn — 🩺 Bác sĩ Mai Gia Linh đã tham gia cuộc hội thoại', time: '06:18' },
      { id: 'm-1213-4', sender: 'doctor', doctorName: 'BS. Mai Gia Linh', avatarLabel: 'GL', text: 'Tôi sẽ ở đây và kết nối chị với hỗ trợ khẩn cấp.', time: '06:19' },
    ],
  },
  {
    id: 'conv-1214',
    sessionCode: '1214',
    patientName: 'Đinh Quốc Huy',
    patientAge: 33,
    branch: 'Chi nhánh B',
    specialty: 'Mắt',
    handlerType: 'bot',
    riskLevel: 'normal',
    rating: 4,
    feedback: 'Hướng dẫn vệ sinh mắt rõ ràng, dễ thực hiện.',
    lastMessage: 'Tôi sẽ đặt lịch nếu mắt còn đỏ sau 24 giờ.',
    updatedMinutesAgo: 173,
    symptoms: ['Đỏ mắt', 'Cộm mắt', 'Chảy nước mắt'],
    botSummary: 'Có thể kích ứng hoặc viêm kết mạc nhẹ, bot hướng dẫn vệ sinh mắt và đặt lịch nếu kéo dài.',
    messages: [
      { id: 'm-1214-1', sender: 'patient', text: 'Mắt tôi đỏ và cộm sau khi đi ngoài đường bụi.', time: '05:42' },
      { id: 'm-1214-2', sender: 'chatbot', text: 'Anh rửa mắt bằng nước muối sinh lý, tránh dụi mắt và không dùng chung khăn.', time: '05:44' },
      { id: 'm-1214-3', sender: 'patient', text: 'Tôi sẽ đặt lịch nếu mắt còn đỏ sau 24 giờ.', time: '05:46' },
    ],
  },
  {
    id: 'conv-1215',
    sessionCode: '1215',
    patientName: 'Hà Bảo Ngọc',
    patientAge: 30,
    branch: 'Chi nhánh C',
    specialty: 'Dinh dưỡng',
    handlerType: 'bot',
    riskLevel: 'normal',
    rating: 2,
    feedback: 'Tôi muốn tư vấn thực đơn cụ thể hơn, câu trả lời hiện tại chưa đủ chi tiết.',
    lastMessage: 'Tôi muốn tư vấn chi tiết hơn về thực đơn.',
    updatedMinutesAgo: 196,
    symptoms: ['Tăng cân nhanh', 'Mệt sau ăn'],
    botSummary: 'Tư vấn dinh dưỡng cơ bản chưa đáp ứng kỳ vọng, người dùng đánh giá thấp.',
    messages: [
      { id: 'm-1215-1', sender: 'patient', text: 'Tôi tăng cân nhanh và hay mệt sau ăn.', time: '05:11' },
      { id: 'm-1215-2', sender: 'chatbot', text: 'Chị nên ghi nhật ký ăn uống 7 ngày và ưu tiên bữa ăn nhiều rau, đạm nạc.', time: '05:12' },
      { id: 'm-1215-3', sender: 'patient', text: 'Tôi muốn tư vấn chi tiết hơn về thực đơn.', time: '05:14' },
    ],
  },
]
